// Got this from FEMapCreator `Terrain_Data.xml`
const terrainIdToName: Record<number, string> = {
  0: "--",
  1: "Plains",
  2: "Road",
  3: "Village Entrance",
  4: "Closed Village Entrance",
  5: "House",
  6: "Armory",
  7: "Vendor",
  8: "Arena",
  10: "Fort",
  11: "Castle Gate",
  12: "Forest",
  13: "Thicket",
  14: "Sand",
  15: "Desert",
  16: "River",
  17: "Hill",
  18: "Peak",
  19: "Bridge",
  21: "Sea",
  22: "Lake",
  23: "Floor",
  25: "Fence",
  26: "Wall",
  27: "Wall",
  29: "Pillar",
  30: "Door",
  31: "Throne",
  32: "Opened Chest",
  33: "Chest",
  34: "Roof",
  35: "Fort Gate",
  37: "Ruins",
  38: "Cliff",
  44: "Castle Wall",
  45: "Stairs",
  46: "Village Wall",
  51: "Snag",
  52: "Snag Bridge",
  53: "Sky",
  54: "Deeps",
  55: "Visitable Ruins",
  56: "Inn",
  57: "Barrel",
  60: "Water",
  61: "Gunnel",
  62: "Deck",
  63: "Brace",
  64: "Mast",
  65: "Crenel",
};

export default terrainIdToName;

